import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

const LANGUAGE_KEY = 'i18nextLng';

const getInitialLanguage = () => {
    if (typeof window !== "undefined") {
        return localStorage.getItem(LANGUAGE_KEY) || 'en';
    }
    return 'en';
};


i18n.use(initReactI18next).init({
    resources: {
        en: {
            translation: {
                "get_started": "Get started",
                "continue_with_phone": "Continue with Phone",
                "or": "OR",
                "check_your_email": "Check your email",
                "verify_email": "We need you to verify your email address.",
                "create_profile": "Create Profile",
                "verify_sign_in": "We'll send a code to this email to verify your sign in.",
                "didnt_receive": "Didn't receive the email? Try checking your junk or spam folders",
                "resend":" Resend",
                "international_films":"International films with voice-over in Russia",
                "upcoming_releases":"Upcoming releases you won't want to miss",
                "choose_interests": "Choose your interests",
                "better_recommendations": "Get better video recommendations",
                "genres": "Genres",
                "shows": "Shows",
                "tap_continue": "By tapping Continue, you agree to our",
                "terms": "Terms",
                "and": "and",
                "privacy_policy": "Privacy Policy",
                "more_like": "More Like This",
                "share_to": "Share to",
                "settings": "Settings",
                "app_settings": "App Settings",
                "manage_profiles": "Manage Profiles",
                "devices": "Devices",
                "app_language": "App Language",
                "support_center": "Support Center",
                "privacy_terms": "Privacy & Terms",
                "who_is_watching": "Who's watching?",
                "id_name": "ID name",
                "email_address": "Email address",
                "display_language": "Display language",
                "english": "English",
                "audio_subtitles": "Audio & Subtitles",
                "english_uk": "English (United Kingdom)",
                "autoplay_next": "Autoplay next episode",
                "autoplay_previews": "Autoplay previews",
                "log_out": "Log out",
                "good_morning": "Good morning",
                "latest_releases": "Latest Releases",
                "fresh_additions": "Fresh additions to our collection.",
                "dubbed_movies": "Dubbed Movies",
                "coming_soon": "Coming Soon",
                "copy_link": "Copy Link",
                "save_video": "Save Video",
                "report": "Report",
                "info": "Info",
                "rating": "Rating",
                "point": "point",
                "review": "Review",
                "watched": "Watched",
                "ai_summary": "This summary is AI-generated.",
                "review_summary": "Review summary",
                "write_review": "Write a Review",
                "tap_star": "Tap a star to rate",
                "download": "Download",
                "space_used": "Space Used",
                "of": "of",
                "delete_movie": "Delete movie?",
                "confirm_delete": "Are you sure you want to delete movie?",
                "action_irreversible": "This action cannot be undone.",
                "cancel": "Cancel",
                "delete": "Delete",
                "studio": "Studio",
                "more_like_this": "More Like This",
                "cast_crew": "Cast & Crew",
                "audio_tracks": "Audio tracks",
                "subtitles": "Subtitles",
                "director": "Director",
                "top_searches": "Top searches",
                "suggested": "Suggested",
                "top_result": "Top Result",
                "franchises": "Franchises",
                "series": "Series",
                "episodes": "Episodes",
                "new_hot": "New & Hot"
            },
        },
        az: {
            translation: {
                "get_started": "Başlayın",
                "continue_with_phone": "Telefonla Devam Et",
                "or": "veya",
                "check_your_email": "E-postanızı kontrol edin",
                "verify_email": "E-posta adresinizi doğrulamanız gerekiyor.",
                "create_profile": "Profil Oluştur",
                "verify_sign_in": "Girişinizi doğrulamak için bu e-postaya bir kod göndereceğiz.",
                "didnt_receive": "E-postayı almadınız mı? Gereksiz veya spam klasörlerinizi kontrol etmeyi deneyin",
                "resend":" Tekrar gönder",
                "international_films":"Rusya'da seslendirilmiş uluslararası filmler",
                "upcoming_releases":"Kaçırmak istemeyeceğiniz yaklaşan yayınlar",
                "choose_interests": "İlgi alanlarınızı seçin",
                "better_recommendations": "Daha iyi video önerileri alın",
                "genres": "Türler",
                "shows": "Gösteriler",
                "tap_continue": "Devam Et'e dokunarak kabul etmiş olursunuz",
                "terms": "Şartlar",
                "and": "ve",
                "privacy_policy": "Gizlilik Politikası",
                "more_like": "Bunun Gibi Daha Fazlası",
                "share_to": "Paylaş",
                "settings": "Ayarlar",
                "app_settings": "Uygulama Ayarları",
                "manage_profiles": "Profilleri Yönet",
                "devices": "Cihazlar",
                "app_language": "Uygulama Dili",
                "support_center": "Destek Merkezi",
                "privacy_terms": "Gizlilik ve Şartlar",
                "who_is_watching": "Kim izliyor?",
                "id_name": "Kimlik Adı",
                "email_address": "E-posta Adresi",
                "display_language": "Görüntüleme Dili",
                "english": "İngilizce",
                "audio_subtitles": "Ses ve Altyazılar",
                "english_uk": "İngilizce (Birleşik Krallık)",
                "autoplay_next": "Bir sonraki bölümü otomatik oynat",
                "autoplay_previews": "Önizlemeleri otomatik oynat",
                "log_out": "Çıkış Yap",
                "good_morning": "Günaydın",
                "latest_releases": "Son Çıkışlar",
                "fresh_additions": "Koleksiyonumuza yeni eklenenler.",
                "dubbed_movies": "Rusya'da seslendirilmiş filmler",
                "coming_soon": "Kaçırmak istemeyeceğiniz yakında çıkacaklar",
                "copy_link": "Bağlantıyı Kopyala",
                "save_video": "Videoyu Kaydet",
                "report": "Şikayet Et",
                "info": "Bilgi",
                "rating": "Puan",
                "point": "Puan",
                "review": "İnceleme",
                "watched": "İzlenmiş",
                "ai_summary": "Bu özet yapay zeka tarafından oluşturulmuştur.",
                "review_summary": "İnceleme Özeti",
                "write_review": "Bir İnceleme Yazın",
                "tap_star": "Puanlamak için bir yıldıza dokunun",
                "download": "İndir",
                "space_used": "Kullanılan Alan",
                "of": "Üzerinden",
                "delete_movie": "Filmi Sil?",
                "confirm_delete": "Filmi silmek istediğinizden emin misiniz?",
                "action_irreversible": "Bu işlem geri alınamaz.",
                "cancel": "İptal",
                "delete": "Sil",
                "studio": "Stüdyo",
                "more_like_this": "Bunlar Gibi Daha Fazlası",
                "cast_crew": "Oyuncular ve Ekip",
                "audio_tracks": "Ses Parçaları",
                "subtitles": "Altyazılar",
                "director": "Yönetmen",
                "top_searches": "Popüler Aramalar",
                "suggested": "Önerilen",
                "top_result": "En İyi Sonuç",
                "franchises": "Seriler",
                "series": "Seriler",
                "episodes": "Bölümler",
                "new_hot": "Yeni ve Popüler"
            },
        },
        ru: {
            translation: {
                "get_started": "Начать",
                "continue_with_phone": "Продолжить с телефона",
                "or": "или",
                "check_your_email": "Проверьте свою электронную почту",
                "verify_email": "Нам необходимо подтвердить ваш адрес электронной почты.",
                "create_profile": "Создать профиль",
                "verify_sign_in": "Мы отправим код на эту почту для подтверждения входа.",
                "didnt_receive": "Не получили письмо? Попробуйте проверить папки \"Нежелательная почта\" или \"Спам\"",
                "resend":" Отправить снова",
                "international_films":"Международные фильмы с озвучкой в России",
                "upcoming_releases":"Предстоящие релизы, которые нельзя пропустить",
                "choose_interests": "Выберите свои интересы",
                "better_recommendations": "Получите лучшие рекомендации по видео",
                "genres": "Жанры",
                "shows": "Шоу",
                "tap_continue": "Нажимая «Продолжить», вы соглашаетесь с нашими",
                "terms": "Условия",
                "and": "и",
                "privacy_policy": "Политика конфиденциальности",
                "more_like": "Похожие на это",
                "share_to": "Поделиться",
                "settings": "Настройки",
                "app_settings": "Настройки приложения",
                "manage_profiles": "Управление профилями",
                "devices": "Устройства",
                "app_language": "Язык приложения",
                "support_center": "Служба поддержки",
                "privacy_terms": "Конфиденциальность и Условия",
                "who_is_watching": "Кто смотрит?",
                "id_name": "Имя пользователя",
                "email_address": "Адрес электронной почты",
                "display_language": "Язык отображения",
                "english": "Английский",
                "audio_subtitles": "Аудио и Субтитры",
                "english_uk": "Английский (Великобритания)",
                "autoplay_next": "Автоматическое воспроизведение следующего эпизода",
                "autoplay_previews": "Автоматическое воспроизведение превью",
                "log_out": "Выйти",
                "good_morning": "Доброе утро",
                "latest_releases": "Последние новинки",
                "fresh_additions": "Свежие дополнения к нашей коллекции.",
                "dubbed_movies": "Фильмы с озвучкой на русском языке",
                "coming_soon": "Скоро в прокате",
                "copy_link": "Копировать ссылку",
                "save_video": "Сохранить видео",
                "report": "Пожаловаться",
                "info": "Информация",
                "rating": "Рейтинг",
                "point": "Баллы",
                "review": "Отзыв",
                "watched": "Просмотрено",
                "ai_summary": "Этот обзор создан искусственным интеллектом.",
                "review_summary": "Резюме отзыва",
                "write_review": "Написать отзыв",
                "tap_star": "Нажмите на звезду, чтобы оценить",
                "download": "Скачать",
                "space_used": "Использовано места",
                "of": "из",
                "delete_movie": "Удалить фильм?",
                "confirm_delete": "Вы уверены, что хотите удалить фильм?",
                "action_irreversible": "Это действие нельзя отменить.",
                "cancel": "Отмена",
                "delete": "Удалить",
                "studio": "Студия",
                "more_like_this": "Похожие",
                "cast_crew": "Актеры и съемочная группа",
                "audio_tracks": "Аудиодорожки",
                "subtitles": "Субтитры",
                "director": "Режиссер",
                "top_searches": "Популярные запросы",
                "suggested": "Предложенные",
                "top_result": "Лучший результат",
                "franchises": "Франшизы",
                "series": "Сериалы",
                "episodes": "Эпизоды",
                "new_hot": "Новинки"
            },
        },
    },
    lng: getInitialLanguage(),
    fallbackLng: 'en',
    interpolation: {
        escapeValue: false,
    },
});

i18n.on('languageChanged', (lng) => {

    if (typeof window !== "undefined") {
        localStorage.setItem(LANGUAGE_KEY, lng);
    }
});

export default i18n;
